package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

// primitives содержит отображение примитивных типов Go к их нулевым значениям
var primitives = map[string]string{
	"int":        "0",
	"int8":       "0",
	"int16":      "0",
	"int32":      "0",
	"int64":      "0",
	"uint":       "0",
	"uint8":      "0",
	"uint16":     "0",
	"uint32":     "0",
	"uint64":     "0",
	"float32":    "0",
	"float64":    "0",
	"complex64":  "0",
	"complex128": "0",
	"byte":       "0",
	"rune":       "0",
	"uintptr":    "0",
	"string":     `""`,
	"bool":       "false",
}

// structInfo содержит информацию о структуре для генерации
type structInfo struct {
	Name   string
	Fields []*ast.Field
}

// packageStructs содержит структуры одного пакета
type packageStructs struct {
	PackageName string
	PackagePath string
	Structs     []structInfo
	Imports     map[string]bool // Импорты, необходимые для сгенерированного кода
}

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	// Получаем текущую рабочую директорию (корень проекта)
	root, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("failed to get working directory: %w", err)
	}

	// Собираем все структуры с // generate:reset по пакетам
	packageMap := make(map[string]*packageStructs)

	err = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		// Пропускаем служебные директории
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "testdata" || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}

		// Обрабатываем только .go файлы (не тестовые и не сгенерированные)
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		// Парсим файл
		dir := filepath.Dir(path)
		structs, pkgName, err := findStructsInFile(path)
		if err != nil {
			return fmt.Errorf("failed to parse %s: %w", path, err)
		}

		if len(structs) > 0 {
			if _, exists := packageMap[dir]; !exists {
				packageMap[dir] = &packageStructs{
					PackageName: pkgName,
					PackagePath: dir,
					Structs:     make([]structInfo, 0),
					Imports:     make(map[string]bool),
				}
			}
			packageMap[dir].Structs = append(packageMap[dir].Structs, structs...)
		}

		return nil
	})

	if err != nil {
		return fmt.Errorf("failed to walk directory tree: %w", err)
	}

	// Генерируем reset.gen.go для каждого пакета
	for _, pkg := range packageMap {
		if err := generateResetFile(pkg); err != nil {
			return fmt.Errorf("failed to generate reset file for package %s: %w", pkg.PackageName, err)
		}
		fmt.Printf("Generated reset.gen.go for package %s (%s)\n", pkg.PackageName, pkg.PackagePath)
	}

	if len(packageMap) == 0 {
		fmt.Println("No structs with // generate:reset comment found")
	}

	return nil
}

// findStructsInFile ищет структуры с комментарием // generate:reset в файле
func findStructsInFile(filePath string) ([]structInfo, string, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return nil, "", err
	}

	var structs []structInfo
	pkgName := file.Name.Name

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}

		// Проверяем комментарий на уровне GenDecl
		hasGenDeclComment := hasGenerateResetComment(genDecl.Doc)

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			// Проверяем комментарий на уровне TypeSpec или GenDecl
			if hasGenDeclComment || hasGenerateResetComment(typeSpec.Doc) {
				structs = append(structs, structInfo{
					Name:   typeSpec.Name.Name,
					Fields: structType.Fields.List,
				})
			}
		}
	}

	return structs, pkgName, nil
}

// hasGenerateResetComment проверяет наличие комментария // generate:reset
func hasGenerateResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, comment := range doc.List {
		if strings.Contains(comment.Text, "generate:reset") {
			return true
		}
	}
	return false
}

// generateResetFile генерирует файл reset.gen.go для пакета
func generateResetFile(pkg *packageStructs) error {
	var buf bytes.Buffer

	// Заголовок файла
	buf.WriteString("// Code generated by reset; DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "// Package %s содержит сгенерированные методы Reset().\n", pkg.PackageName)
	fmt.Fprintf(&buf, "package %s\n\n", pkg.PackageName)

	// Собираем импорты из всех структур
	for _, s := range pkg.Structs {
		collectImports(s.Fields, pkg.Imports)
	}

	// Добавляем импорты если они есть
	if len(pkg.Imports) > 0 {
		buf.WriteString("import (\n")
		for imp := range pkg.Imports {
			buf.WriteString(fmt.Sprintf("\t%q\n", imp))
		}
		buf.WriteString(")\n\n")
	}

	// Генерируем метод Reset() для каждой структуры
	for _, s := range pkg.Structs {
		if err := generateResetMethod(&buf, s); err != nil {
			return fmt.Errorf("failed to generate Reset method for %s: %w", s.Name, err)
		}
		buf.WriteString("\n")
	}

	// Форматируем код
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("failed to format generated code: %w\n%s", err, buf.String())
	}

	// Записываем файл
	outputPath := filepath.Join(pkg.PackagePath, "reset.gen.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return fmt.Errorf("failed to write file: %w", err)
	}

	return nil
}

// generateResetMethod генерирует метод Reset() для структуры
func generateResetMethod(buf *bytes.Buffer, s structInfo) error {
	receiver := strings.ToLower(s.Name[:1])

	fmt.Fprintf(buf, "func (%s *%s) Reset() {\n", receiver, s.Name)
	fmt.Fprintf(buf, "\tif %s == nil {\n", receiver)
	buf.WriteString("\t\treturn\n")
	buf.WriteString("\t}\n\n")

	// Генерируем код сброса для каждого поля
	for _, field := range s.Fields {
		if len(field.Names) == 0 {
			// Встроенное поле (embedded field)
			continue
		}

		for _, fieldName := range field.Names {
			// Обрабатываем все поля (и экспортируемые, и неэкспортируемые)
			resetCode := generateFieldReset(receiver, fieldName.Name, field.Type)
			if resetCode != "" {
				buf.WriteString(resetCode)
			}
		}
	}

	buf.WriteString("}\n")
	return nil
}

// generateFieldReset генерирует код сброса для одного поля
func generateFieldReset(receiver, fieldName string, fieldType ast.Expr) string {
	var buf bytes.Buffer
	fieldAccess := fmt.Sprintf("%s.%s", receiver, fieldName)

	switch t := fieldType.(type) {
	case *ast.Ident:
		// Примитивный тип или именованный тип
		if zeroVal, isPrimitive := primitives[t.Name]; isPrimitive {
			buf.WriteString(fmt.Sprintf("\t%s = %s\n", fieldAccess, zeroVal))
		} else {
			// Именованный тип (возможно структура с методом Reset())
			buf.WriteString(fmt.Sprintf("\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", fieldAccess))
			buf.WriteString("\t\tresetter.Reset()\n")
			buf.WriteString("\t}\n")
		}

	case *ast.StarExpr:
		// Указатель
		return generatePointerReset(receiver, fieldName, fieldAccess, t.X)

	case *ast.ArrayType:
		// Массив или слайс
		if t.Len == nil {
			// Слайс
			buf.WriteString(fmt.Sprintf("\t%s = %s[:0]\n", fieldAccess, fieldAccess))
		} else {
			// Массив - сбрасываем каждый элемент
			buf.WriteString(fmt.Sprintf("\t// Array field %s - implement if needed\n", fieldName))
		}

	case *ast.MapType:
		// Мапа
		buf.WriteString(fmt.Sprintf("\tclear(%s)\n", fieldAccess))

	case *ast.SelectorExpr:
		// Квалифицированный тип (например, time.Time)
		buf.WriteString(fmt.Sprintf("\t%s = %s{}\n", fieldAccess, formatType(t)))

	case *ast.InterfaceType:
		// Интерфейс
		buf.WriteString(fmt.Sprintf("\t%s = nil\n", fieldAccess))

	case *ast.ChanType:
		// Канал
		buf.WriteString(fmt.Sprintf("\t%s = nil\n", fieldAccess))

	case *ast.FuncType:
		// Функция
		buf.WriteString(fmt.Sprintf("\t%s = nil\n", fieldAccess))

	case *ast.StructType:
		// Встроенная структура
		buf.WriteString(fmt.Sprintf("\t%s = %s{}\n", fieldAccess, fieldName))

	default:
		// Неизвестный тип - оставляем комментарий
		buf.WriteString(fmt.Sprintf("\t// Unknown type for field %s\n", fieldName))
	}

	return buf.String()
}

// generatePointerReset генерирует код сброса для указателя
func generatePointerReset(receiver, fieldName, fieldAccess string, elemType ast.Expr) string {
	var buf bytes.Buffer

	buf.WriteString(fmt.Sprintf("\tif %s != nil {\n", fieldAccess))

	switch t := elemType.(type) {
	case *ast.Ident:
		// Указатель на примитив или именованный тип
		if zeroVal, isPrimitive := primitives[t.Name]; isPrimitive {
			buf.WriteString(fmt.Sprintf("\t\t*%s = %s\n", fieldAccess, zeroVal))
		} else {
			// Указатель на именованный тип (возможно структура)
			buf.WriteString(fmt.Sprintf("\t\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", fieldAccess))
			buf.WriteString("\t\t\tresetter.Reset()\n")
			buf.WriteString("\t\t}\n")
		}

	case *ast.SelectorExpr:
		// Указатель на квалифицированный тип
		buf.WriteString(fmt.Sprintf("\t\t*%s = %s{}\n", fieldAccess, formatType(t)))

	case *ast.StructType:
		// Указатель на структуру
		buf.WriteString(fmt.Sprintf("\t\t*%s = %s{}\n", fieldAccess, fieldName))

	default:
		// Указатель на сложный тип
		buf.WriteString(fmt.Sprintf("\t\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n", fieldAccess))
		buf.WriteString("\t\t\tresetter.Reset()\n")
		buf.WriteString("\t\t}\n")
	}

	buf.WriteString("\t}\n")
	return buf.String()
}

// collectImports собирает импорты, необходимые для полей структуры
func collectImports(fields []*ast.Field, imports map[string]bool) {
	for _, field := range fields {
		collectImportsFromType(field.Type, imports)
	}
}

// collectImportsFromType рекурсивно собирает импорты из типа
func collectImportsFromType(expr ast.Expr, imports map[string]bool) {
	switch t := expr.(type) {
	case *ast.SelectorExpr:
		// Квалифицированный тип (например, time.Time, pkg.Type)
		if ident, ok := t.X.(*ast.Ident); ok {
			// Добавляем известные пакеты стандартной библиотеки
			switch ident.Name {
			case "time":
				imports["time"] = true
			case "context":
				imports["context"] = true
			case "sync":
				imports["sync"] = true
				// Можно добавить другие известные пакеты
			}
		}
	case *ast.StarExpr:
		collectImportsFromType(t.X, imports)
	case *ast.ArrayType:
		collectImportsFromType(t.Elt, imports)
	case *ast.MapType:
		collectImportsFromType(t.Key, imports)
		collectImportsFromType(t.Value, imports)
	}
}

// formatType преобразует ast.Expr в строковое представление типа
func formatType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", formatType(t.X), t.Sel.Name)
	case *ast.StarExpr:
		return "*" + formatType(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + formatType(t.Elt)
		}
		return fmt.Sprintf("[%s]%s", formatType(t.Len), formatType(t.Elt))
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", formatType(t.Key), formatType(t.Value))
	default:
		return "unknown"
	}
}
