// Code generated by reset; DO NOT EDIT.

package example

func (p *Pool) Reset() {
	if p == nil {
		return
	}

	p.Items = p.Items[:0]
	p.Counter = 0
	p.Active = false
}

func (b *Buffer) Reset() {
	if b == nil {
		return
	}

	b.Data = b.Data[:0]
	clear(b.Metadata)
	b.Size = 0
}
